import enum


class _Operation(enum.Enum):
    CREATE_STUDY = 0
    CREATE_TRIAL = 1
    SET_STUDY_USER_ATTR = 2
    SET_STUDY_SYSTEM_ATTR = 3
    SET_STUDY_DIRECTIONS = 4
    SET_TRIAL_PARAM = 5
    SET_TRIAL_VALUES = 6
    SET_TRIAL_USER_ATTR = 7
    SET_TRIAL_SYSTEM_ATTR = 8
    SET_TRIAL_STATE = 9
    SET_TRIAL_INTERMEDIATE_VALUE = 10
